version: '3'

services:

  ciblog-web:
    container_name: ciblog
    build: .
    depends_on:
      - ciblog-db
    ports:
      - '80:80'
    volumes: 
      - .:/var/www/html/:Z
  
  ciblog-db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ciblog
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    volumes:
      - ./assets/sql:/docker-entrypoint-initdb.d

