apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciblog-web
  namespace: default
spec:
  selector:
    matchLabels:
      app: ciblog-web
  template:
    metadata:
      labels:
        app: ciblog-web
    spec:
      containers:
      - name: ciblog-web
        image: josephsim/ciblog-web
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciblog-db
  namespace: default
spec:
  selector:
    matchLabels:
      app: ciblog-db
  template:
    metadata:
      labels:
        app: ciblog-db
    spec:
      containers:
      - name: ciblog-db
        image: josephsim/ciblog-db
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "ciblog"
        - name: MYSQL_INITDB_SKIP_TZINFO
          value: "yes"

---

apiVersion: v1
kind: Service
metadata:
  name: ciblog-web
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ciblog-web

---

apiVersion: v1
kind: Service
metadata:
  name: ciblog-db
  namespace: default
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: ciblog-db

